# Generated by Django 3.0.8 on 2021-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='titile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
