# Generated by Django 3.0.8 on 2021-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210226_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
