# Generated by Django 3.0.8 on 2021-02-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210227_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teamvar', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('filtag', models.CharField(blank=True, max_length=200, null=True)),
                ('insta', models.CharField(blank=True, max_length=300, null=True)),
                ('lin', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.CharField(max_length=600)),
                ('pic', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
            ],
        ),
    ]
